Fix testcode
kenchasonakai/rspec_app_exam pull request #1
Opened 2020-11-01 04:57 UTC by kenchasonakai

### 概要
spec/system/task_spec.rbのTODOとFIXMEの修正を行いました
### コメント
書き方等おかしなところがありましたらご指摘お願いします。
### 参考資料
https://qiita.com/at-946/items/a873ed88aef3a81e43d6
https://qiita.com/ShotaroHirose59/items/7c64be350676120de9bd
### 確認方法
### 確認したこと
### 修正内容
baf2585 55c40b0 local変数での定義をletに置き換えました
55ebf1c テストの日付表示形式を%m/%d %H:%Mに変更しました
b09bcfb 確認したいタイトルの文字列がフラッシュメーッセージの中に含まれてしまっていたため、テスト条件を"タスクのタイトルが表示されていないこと"から"削除時のフラッシュメッセージが表示されていること"に変更しました
d99b198 別タブで開いたページのテストができるように修正しました

2020-11-02 04:24 UTC, yuji91 requested changes
1点だけ修正お願いします！

難しい問題もあったかと思いますが、実際は余裕だったという感じでしょうか？😅

2020-11-02 04:24 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
本来確認したかった「削除したタスクのタイトルが表示されていないこと」という確認観点が変わってしまっているので、画面上をどのように確認すれば同観点が正しく確認できるかを考えてみましょう！

2020-11-03 04:06 UTC, kenchasonakai commented on spec/system/task_spec.rb
> +        expect(page).to have_content "Task was successfully destroyed."
b3500a2 にてタスクのタイトルが表示されていないことを確認するように修正しました。
findにてCSSセレクタを指定してその範囲内で文字の確認をするようにしました

2020-11-04 03:16 UTC, yuji91 approved these changes
LGTMです！
![LGTM_Gakky](https://user-images.githubusercontent.com/28836274/98065254-942ffd00-1e97-11eb-84b0-d596c754781c.png)

2020-11-04 03:16 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
1行で記載することもできますが、今のままでも大丈夫です！
```suggestion
        switch_to_window(windows.last)
```

2020-11-04 08:00 UTC, kenchasonakai commented
> 難しい問題もあったかと思いますが、実際は余裕だったという感じでしょうか？😅
ヒントで実装を確認してみようって書いてあったのでなんとかなりました！

2020-11-04 08:11 UTC, merged